/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeBox: typeof import('./components/CodeBox.vue')['default']
    ConfigPanel: typeof import('./components/ConfigPanel.vue')['default']
    Dock: typeof import('./components/Dock.vue')['default']
    LanguageIcon: typeof import('./components/LanguageIcon.vue')['default']
    LightBorderFrame: typeof import('./components/light-border-frame.vue')['default']
    MacosWindow: typeof import('./components/macos-window.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleTab: typeof import('./components/StyleTab.vue')['default']
    VisionosWindow: typeof import('./components/visionos-window.vue')['default']
  }
}
